// Demo data for the Instagram MVP clone
// Used when Supabase is not configured

export const DEMO_USERS = [
    {
        id: 'user-1',
        username: 'alex.morgan',
        full_name: 'Alex Morgan',
        bio: '📸 Photographer | ✈️ Traveler | 🌅 Living for the golden hour',
        avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex&backgroundColor=b6e3f4',
        posts_count: 142,
        followers_count: 12400,
        following_count: 892,
    },
    {
        id: 'user-2',
        username: 'sarah.design',
        full_name: 'Sarah Chen',
        bio: '🎨 UI/UX Designer at Google | 🎯 Making pixels perfect',
        avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah&backgroundColor=ffd5dc',
        posts_count: 89,
        followers_count: 8900,
        following_count: 456,
    },
    {
        id: 'user-3',
        username: 'mike.dev',
        full_name: 'Mike Johnson',
        bio: '💻 Full Stack Developer | 🚀 Building the future | 🎮 Gamer',
        avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mike&backgroundColor=c0aede',
        posts_count: 67,
        followers_count: 5600,
        following_count: 234,
    },
    {
        id: 'user-4',
        username: 'emma.travels',
        full_name: 'Emma Wilson',
        bio: '🌍 Travel blogger | 📍 Currently in Bali | ✨ Living my best life',
        avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emma&backgroundColor=d1d4f9',
        posts_count: 234,
        followers_count: 45000,
        following_count: 678,
    },
    {
        id: 'user-5',
        username: 'james.fitness',
        full_name: 'James Brown',
        bio: '💪 Fitness Coach | 🥑 Nutrition Expert | 🏋️ Transform your life',
        avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=james&backgroundColor=ffdfbf',
        posts_count: 312,
        followers_count: 28000,
        following_count: 120,
    },
    {
        id: 'user-6',
        username: 'lisa.art',
        full_name: 'Lisa Park',
        bio: '🎭 Digital Artist | 🖌️ Creating worlds one pixel at a time',
        avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lisa&backgroundColor=c1f0c1',
        posts_count: 178,
        followers_count: 15600,
        following_count: 543,
    },
];

export const DEMO_POSTS = [
    {
        id: 'post-1',
        user: DEMO_USERS[3],
        media_url: 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=600&h=600&fit=crop',
        media_type: 'image',
        caption: 'Golden hour in Bali 🌅 There\'s nothing quite like watching the sun melt into the ocean from a clifftop temple. This island never stops surprising me ✨',
        likes_count: 2847,
        comments_count: 134,
        created_at: '2h',
        liked: false,
        saved: false,
    },
    {
        id: 'post-2',
        user: DEMO_USERS[0],
        media_url: 'https://images.unsplash.com/photo-1682687220742-aba13b6e50ba?w=600&h=600&fit=crop',
        media_type: 'image',
        caption: 'Streets of Tokyo at night 🗼 The neon lights make every corner look like a movie scene. More from this series coming soon! 📸',
        likes_count: 4512,
        comments_count: 267,
        created_at: '4h',
        liked: true,
        saved: false,
    },
    {
        id: 'post-3',
        user: DEMO_USERS[1],
        media_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&h=600&fit=crop',
        media_type: 'image',
        caption: 'New design system just dropped 🎨 Been working on this color palette for weeks. Gradient game strong 💪',
        likes_count: 1893,
        comments_count: 89,
        created_at: '6h',
        liked: false,
        saved: true,
    },
    {
        id: 'post-4',
        user: DEMO_USERS[4],
        media_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=600&fit=crop',
        media_type: 'image',
        caption: 'Morning workout done ✅ Consistency is key! Remember, the only bad workout is the one you didn\'t do 🏋️‍♂️ #fitness #motivation',
        likes_count: 6234,
        comments_count: 342,
        created_at: '8h',
        liked: false,
        saved: false,
    },
    {
        id: 'post-5',
        user: DEMO_USERS[5],
        media_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&h=600&fit=crop',
        media_type: 'image',
        caption: 'My latest digital painting 🎨 "City of Dreams" - about 40 hours of work went into this piece. What do you think?',
        likes_count: 3421,
        comments_count: 156,
        created_at: '12h',
        liked: false,
        saved: false,
    },
    {
        id: 'post-6',
        user: DEMO_USERS[2],
        media_url: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&h=600&fit=crop',
        media_type: 'image',
        caption: 'New setup who dis 💻🔥 Finally upgraded to the M3 Max. The speed difference is insane for builds. Dev life is good 🚀',
        likes_count: 2156,
        comments_count: 198,
        created_at: '1d',
        liked: true,
        saved: false,
    },
];

export const DEMO_STORIES = [
    { id: 'story-1', user: DEMO_USERS[0], media_url: 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=400&h=700&fit=crop', viewed: false },
    { id: 'story-2', user: DEMO_USERS[1], media_url: 'https://images.unsplash.com/photo-1618005198919-d3d4b5a92ead?w=400&h=700&fit=crop', viewed: false },
    { id: 'story-3', user: DEMO_USERS[3], media_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&h=700&fit=crop', viewed: false },
    { id: 'story-4', user: DEMO_USERS[4], media_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=700&fit=crop', viewed: true },
    { id: 'story-5', user: DEMO_USERS[5], media_url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=700&fit=crop', viewed: false },
    { id: 'story-6', user: DEMO_USERS[2], media_url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400&h=700&fit=crop', viewed: true },
];

export const DEMO_REELS = [
    {
        id: 'reel-1',
        user: DEMO_USERS[3],
        video_url: 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=400&h=700&fit=crop',
        caption: 'Bali sunsets hit different 🌅 #travel #bali #sunset',
        likes_count: 45200,
        comments_count: 1234,
        shares_count: 567,
        music: 'Sunset Vibes - Chillhop',
    },
    {
        id: 'reel-2',
        user: DEMO_USERS[4],
        video_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=700&fit=crop',
        caption: '5 exercises for a perfect morning routine 💪 Save this for later!',
        likes_count: 89300,
        comments_count: 5678,
        shares_count: 12400,
        music: 'Motivation - Workout Mix',
    },
    {
        id: 'reel-3',
        user: DEMO_USERS[5],
        video_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=400&h=700&fit=crop',
        caption: 'Watch me create this in Procreate ✨ 40 hours in 60 seconds',
        likes_count: 23100,
        comments_count: 890,
        shares_count: 3450,
        music: 'Lo-fi Study Beats',
    },
    {
        id: 'reel-4',
        user: DEMO_USERS[0],
        video_url: 'https://images.unsplash.com/photo-1682687220742-aba13b6e50ba?w=600&h=1000&fit=crop',
        caption: 'Tokyo at 3AM 🌃 The city never sleeps #tokyo #japan #nightlife',
        likes_count: 67800,
        comments_count: 3456,
        shares_count: 8900,
        music: 'Tokyo Drift - Remix',
    },
];

export const DEMO_CONVERSATIONS = [
    {
        id: 'conv-1',
        user: DEMO_USERS[1],
        lastMessage: 'Hey! Love your latest post 😍',
        time: '2m',
        unread: true,
        online: true,
    },
    {
        id: 'conv-2',
        user: DEMO_USERS[3],
        lastMessage: 'Can you send me those travel photos?',
        time: '15m',
        unread: true,
        online: true,
    },
    {
        id: 'conv-3',
        user: DEMO_USERS[2],
        lastMessage: 'The code review looks good 👍',
        time: '1h',
        unread: false,
        online: false,
    },
    {
        id: 'conv-4',
        user: DEMO_USERS[4],
        lastMessage: 'See you at the gym tomorrow?',
        time: '3h',
        unread: false,
        online: true,
    },
    {
        id: 'conv-5',
        user: DEMO_USERS[5],
        lastMessage: 'Thanks for the feedback on my artwork!',
        time: '1d',
        unread: false,
        online: false,
    },
];

export const DEMO_MESSAGES = [
    { id: 'msg-1', sender: 'other', text: 'Hey! How are you? 😊', time: '10:30 AM' },
    { id: 'msg-2', sender: 'me', text: 'Hey! I\'m doing great, thanks. Just got back from a shoot 📸', time: '10:32 AM' },
    { id: 'msg-3', sender: 'other', text: 'Oh nice! Where did you go this time?', time: '10:33 AM' },
    { id: 'msg-4', sender: 'me', text: 'Downtown Tokyo! The neon lights at night are absolutely insane 🗼', time: '10:35 AM' },
    { id: 'msg-5', sender: 'other', text: 'That sounds amazing!! I saw your latest post, the colors are incredible', time: '10:36 AM' },
    { id: 'msg-6', sender: 'me', text: 'Thank you! I spent hours editing to get the colors just right', time: '10:38 AM' },
    { id: 'msg-7', sender: 'other', text: 'It definitely shows! Have you tried using the new Lightroom presets?', time: '10:40 AM' },
    { id: 'msg-8', sender: 'me', text: 'Not yet but I\'ve been meaning to check them out. Any recommendations?', time: '10:42 AM' },
    { id: 'msg-9', sender: 'other', text: 'Love your latest post 😍', time: '10:45 AM' },
];

export const DEMO_COMMENTS = [
    { id: 'c-1', user: DEMO_USERS[1], text: 'Absolutely stunning! 😍', time: '2h', likes: 24 },
    { id: 'c-2', user: DEMO_USERS[2], text: 'Where is this? I need to visit!', time: '1h', likes: 12 },
    { id: 'c-3', user: DEMO_USERS[4], text: 'The composition is perfect 👌', time: '45m', likes: 8 },
    { id: 'c-4', user: DEMO_USERS[5], text: 'Goals! Adding this to my bucket list ✈️', time: '30m', likes: 5 },
    { id: 'c-5', user: DEMO_USERS[0], text: 'Thank you all! ❤️', time: '15m', likes: 18 },
];

export const DEMO_EXPLORE_IMAGES = [
    'https://images.unsplash.com/photo-1682687220742-aba13b6e50ba?w=300&h=300&fit=crop',
    'https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=300&h=300&fit=crop',
    'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=300&h=300&fit=crop',
    'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=300&h=300&fit=crop',
    'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=300&h=300&fit=crop',
    'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=300&h=300&fit=crop',
    'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=300&h=300&fit=crop',
    'https://images.unsplash.com/photo-1618005198919-d3d4b5a92ead?w=300&h=300&fit=crop',
    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=300&h=300&fit=crop',
    'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=300&h=300&fit=crop',
    'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=300&h=300&fit=crop',
    'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=300&h=300&fit=crop',
];
